// Generated by https://quicktype.io

export interface GetComments {
	feature: Feature;
	comments: Comments;
}

export interface Comments {
	quantity: number;
	comment: Comment[];
}

export interface Comment {
	id: number;
	content: string;
	feature_id: number;
	created_at: string;
	updated_at: string;
}

export interface Feature {
	id: number;
	id_feature: string;
	magnitude: string;
	place: string;
	time: string;
	tsunami: boolean;
	mag_type: string;
	title: string;
	url: string;
	longitude: string;
	latitude: string;
	created_at: string;
	updated_at: string;
}
