// Generated by https://quicktype.io

export interface Earthquakes {
	data: Earthquake[];
	pagination: Pagination;
}

export interface Earthquake {
	id: number;
	type: string;
	attribute: Attribute;
	links: Links;
}

export interface Attribute {
	external_id: string;
	magnitude: number;
	place: string;
	time: string;
	tsunami: boolean;
	mag_type: string;
	title: string;
	coordinates: Coordinates;
}

export interface Coordinates {
	longitude: number;
	latitude: number;
}

export interface Links {
	external_url: string;
}

export interface Pagination {
	current_page: number;
	total: number;
	per_page: number;
}
